### ISSUE TITLE
生成过程中出现的错误提示

### ISSUE THREAD

**Issue by lower01** [samxuxiang/BrepGen#12]
Hello, during the generation process, will Vertex detection failed and Edge detection failed have any impact? I loaded the model and generated a CAD file in the corresponding folder, both in step and stl formats, which can be displayed normally, but these two error prompts appeared during the generation process. Is there any problem?

**Comment by samxuxiang** [comment]
Hi @lower01 , during generation some solids will fail due to non-watertight and other issues. That is why those errors occured during the post-process. The default will generate CAD models in batches with some ratio of failures.

**Comment by lower01** [comment]
> Hi @lower01 , during generation some solids will fail due to non-watertight and other issues. That is why those errors occured during the post-process. The default will generate CAD models in batches with some ratio of failures.



> Hi @lower01 , during generation some solids will fail due to non-watertight and other issues. That is why those errors occured during the post-process. The default will generate CAD models in batches with some ratio of failures.

Thank you for your reply. I have another question to ask. In your project, only the generation process based on the furniture dataset can set category labels for conditional generation, while the generation process based on the DeepCAD and ABC datasets is randomly generated. The reason is that the DeepCAD and ABC datasets themselves do not have category labels, which means labels do not participate in training. However, the furniture dataset itself has category labels, so did labels participate in training?

**Comment by samxuxiang** [comment]
Hi @lower01 , in the training code you have the option to perform classifier-free if label is available, thanks.
