### ISSUE TITLE
Questions about Furniture dataset and checkpoints

### ISSUE THREAD

**Issue by YuiNsky** [samxuxiang/BrepGen#18]
The result of furniture part is quite interesting, can you provide the dataset and checkpoints again?

**Comment by samxuxiang** [comment]
Hi @YuiNsky the furniture data is now available. Due to privacy issue we can not direcly upload the step files. But you can download them using the uid provided in the json file. Thank you.

**Comment by YuiNsky** [comment]
Thanks for your reply. Still, if the dataset can not be provided, can you provide the  Pretrained Checkpoint of the furniture data.

**Comment by lancebing2024-bit** [comment]
> Hi [@YuiNsky](https://github.com/YuiNsky) the furniture data is now available. Due to privacy issue we can not direcly upload the step files. But you can download them using the uid provided in the json file. Thank you.

Thank you so much for providing this valuable work!
I saw your comment mentioning that we can "download them using the uid provided in the json file." I'm now trying to write a Python script to batch-download these STEP files.
I understand that these UIDs (did, wid, eid) are for the Onshape API, and I've been trying to use the onshape-client library for Python. However, I'm running into some issues,Could you please provide a working code snippet for downloading the files, or point me to the correct API methods to request an export and check its status in the current version of the library? Alternatively, if a specific version of onshape-client is required, could you let me know which version to use?

**Comment by Peter-Panhongyu** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you！Hongyu PanEmail: ***@***.***:+86-17353995408

**Comment by lancebing2024-bit** [comment]
Thank you so much for providing this valuable work!
I saw your comment mentioning that we can "download them using the uid
provided in the json file." I'm now trying to write a Python script to
batch-download these STEP files.
I understand that these UIDs (did, wid, eid) are for the Onshape API, and
I've been trying to use the onshape-client library for Python. However, I'm
running into some issues,Could you please provide a working code snippet
for downloading the files, or point me to the correct API methods to
request an export and check its status in the current version of the
library? Alternatively, if a specific version of onshape-client is
required, could you let me know which version to use?
