### ISSUE TITLE
Errors related to data preprocessing

### ISSUE THREAD

**Issue by hxngiee** [samxuxiang/BrepGen#3]
Thank you so much for sharing your amazing work @samxuxiang 

I think this is a very interesting CAD generation work following hnc-cad

While preprocessing the data to understand the contents of this paper, the following error occurred 
```
Traceback (most recent call last):
  File "/root/projects/BrepGen/data_process/process_brep.py", line 7, in <module>
    from occwl.io import load_step
  File "/root/anaconda3/envs/brepgen/lib/python3.9/site-packages/occwl/io.py", line 13, in <module>
    @deprecated(target=None, deprecated_in="0.0.3", remove_in="0.0.5")
TypeError: deprecated() got an unexpected keyword argument 'target'
```
Should I change my version of occwl?

**Comment by samxuxiang** [comment]
Thank you for raising this issue. We use the latest version of occwl. Please try installing again with `mamba install occwl -c lambouj -c conda-forge`, let me know if this solves the problem or not. Thanks.

**Comment by hxngiee** [comment]
Thank you for your quick response @samxuxiang.

Actually, I had trouble installing mamba on my computer, so I fixed it by [commenting out the existing library import](https://github.com/samxuxiang/BrepGen/blob/ab0063661ec5fc581f6b9edf86398809ef6940ee/data_process/process_brep.py#L7), removing the decorator, and importing the function from occwl instead as bellow.

```
# from occwl.io import load_step
from occwl.compound import Compound
def load_single_compound_from_step(step_filename):
    """
    Load data from a STEP file as a single compound

    Args:
        step_filename (str): Path to STEP file

    Returns:
        List of occwl.Compound: a single compound containing all shapes in
                                the file
    """
    return Compound.load_from_step(step_filename)
def load_step(step_filename):
    """Load solids from a STEP file

    Args:
        step_filename (str): Path to STEP file

    Returns:
        List of occwl.Solid: a list of solid models from the file
    """
    compound = load_single_compound_from_step(step_filename)
    return list(compound.solids())
```

Additionally, although it is not an important issue, [when saving preprocessed data as pkl](https://github.com/samxuxiang/BrepGen/blob/ab0063661ec5fc581f6b9edf86398809ef6940ee/data_process/process_brep.py#L190), the last data extension of data['uid'] had to be sliced (When experimenting on a Furniture dataset, it ended in .step, so I slice it.).
```
# save_path = os.path.join(save_folder, data['uid']+'.pkl')
save_path = os.path.join(save_folder, data['uid'][:-5] + '.pkl')
```

Lastly, as a newbie in the CAD domain, I have one question. It seems like this model might work in a multi-solid format, but I am curious if it only operates in a [single solid format](https://github.com/samxuxiang/BrepGen/blob/ab0063661ec5fc581f6b9edf86398809ef6940ee/data_process/process_brep.py#L167).

Thanks a lot!

**Comment by samxuxiang** [comment]
Thank you so much for reporting the issues. Data processing code has been updated. Regarding your last question, the release version of brepgen works on single solid cad model. Although it is easy to extend to multi-solids by adding another diffusion module that denoises the bbox for each component. GPU memory usage will likely be an issue and some tuning need to be done to make the network more efficient.
