### ISSUE TITLE
VAE reconstruction and rendering problems

### ISSUE THREAD

**Issue by ddddddy1221** [samxuxiang/BrepGen#4]
I would like to ask whether the VAE model has the code of the reconstruction part, and what methods or tools are used in the rendering part of your paper?

**Comment by samxuxiang** [comment]
Hi, you can [decode the normalized edge or surface points](https://github.com/samxuxiang/BrepGen/blob/1b54431725d6ec44099af902384add1d6dbb411e/sample.py#L348-L351), and then given its bbox location and dimension, [restore it back to the global coordinate](https://github.com/samxuxiang/BrepGen/blob/1b54431725d6ec44099af902384add1d6dbb411e/sample.py#L323-L324). You can visualize the points with pyplot scatter. We use [BlenderToolbox](https://github.com/HTDerekLiu/BlenderToolbox) to plot the figures in the paper (they have demo for plotting pointcloud). Thank you.

**Comment by ddddddy1221** [comment]
> Hi, you can [decode the normalized edge or surface points](https://github.com/samxuxiang/BrepGen/blob/1b54431725d6ec44099af902384add1d6dbb411e/sample.py#L348-L351), and then given its bbox location and dimension, [restore it back to the global coordinate](https://github.com/samxuxiang/BrepGen/blob/1b54431725d6ec44099af902384add1d6dbb411e/sample.py#L323-L324). You can visualize the points with pyplot scatter. We use [BlenderToolbox](https://github.com/HTDerekLiu/BlenderToolbox) to plot the figures in the paper. Thank you.

OK, Thank you very much for your answer.
