### ISSUE TITLE
solidgen code repository link

### ISSUE THREAD

**Issue by lx1037** [samxuxiang/BrepGen#7]
Hi! Thank you for your great work and for sharing the code! 

I'm reproducing BrepGen and SolidGen, which were compared in the paper. However, I'm having trouble finding the code repository for SolidGen. Could you please let me know where I can find the code?

Thank you!!

Best regards,
ziyu

**Comment by samxuxiang** [comment]
Hi @lx1037, for solidgen you can reach out to the paper's authors for the source code. Thank you.
