### ISSUE TITLE
Conditional Generation

### ISSUE THREAD

**Issue by LaFeuilleMorte** [samxuxiang/BrepGen#8]
Thanks for your brilliant work. Can we use other condition to generate objects? If we train the b-rep model along with images/text, can we generate objects given image/text prompt? Another question about the dataset: Can we use meshes or pointclouds to train this model , as B-Rep model datasets are still very small.

**Comment by samxuxiang** [comment]
Hi @LaFeuilleMorte, you can modifify the network to take in other conditions. We did this for the furniture dataset using class embedding. The data representation between pointcloud and brep is very different. There are better model (e.g point-e) for pointcloud generation if you are interested.
