### ISSUE TITLE
硬件需求咨询

### ISSUE THREAD

**Issue by lower01** [samxuxiang/BrepGen#9]
您好，请问这个项目大概需要多少显存的GPU支持呢？

**Comment by samxuxiang** [comment]
Hi @lower01 , a minimum of four GPU with 24GB memory should work if you reduce the batch size for edge latent diffusion module.

**Comment by lower01** [comment]
> Hi @lower01 , for training, a minimum of four GPU with 24GB memory should work if you reduce the batch size for edge latent diffusion module.

Thank you for  your reply!
If I want to run a quick example right now and use the pre-trained model you provided, I don't need to download the data and train the model, right? Then the GPU requirements should be smaller if I load the model directly.
